---
# yaml-language-server: $schema=https://kubernetes-schemas.perry.cafe/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: &cluster postgres17
spec:
  schedule: "@daily"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: *cluster
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
