---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: onepassword-connect
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: glauth
      app.kubernetes.io/name: glauth
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: authelia
            app.kubernetes.io/name: authelia
