---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: glauth
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: glauth
      app.kubernetes.io/name: glauth
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: authelia
            app.kubernetes.io/name: authelia
        - matchLabels:
            app.kubernetes.io/instance: kube-prometheus-stack
            app.kubernetes.io/name: prometheus
            ## Namespace where external-secret lives. Can be removed if they're in the same namespace
            k8s:io.kubernetes.pod.namespace: observability
