# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-tools-secret
stringData:
    config.yaml: ENC[AES256_GCM,data:JoeoHrGrb+g59jsDykT2gTh37DrWWZNtpeWZU1EdXSANIBdFNHYRA7Fy1sVWX+brKk9vGDjjfoA4ViXJIqoc+HZYsEBaVUyqRJHi+cQ4lzJQMLpUOKH19M3JVi8CONcrQMOypfZD9CjM2OP3cKbw3Q12Egt7NCLyApofyvLSsrmzO2s+Zg0xL6tJ7hDGFLh3DBYViMGEpruhAuX2NsC4ctWzF4EpScPbGJ80DgvoJED36XQt6ArlyqiZviK9Z5aHyQXydarXnZRTRilD2VzRHReCdDTYyxPVbDvQfu1gKCgjK9qfx1fK3w+EkYgqm3nSOVR2LZ4s7ttWfTcMoxQU7OGL2TsO01sgk6BH0mGtNSZy+Pb23mUy0sinCiaZVTBouinHTgir5PS5sCCmE8hpmc8AzTZmttiMjvQgZlGkS3TSXNh39uYNEsNtq6OGAS54qMZpwcNoywBnURq434uB/Kty1Ib5JzNFi7olS6A7AVz+JKYB+C/l5Hx66qtQsbymvRo+ou9rsPm6J1/eLVTXf6krfxuLsX65EhNBnl28KkaoZRd3Hb883Oo/pj1/mBResRYEFIQp5WBI+30ph75JCSRv4MhmbDBBPbO1PZXZn7T/zJseGIZp9sEfOLPWaMKhsAVfYjPhyUrNkJAMiu/q3fhVyj8EELTD0aEn1wK/XSrFz7GC9P4gWGWCNHl+39Q91ELuBgQq0LtjtIYm4m0Yf8l0SIawAKH3Us/VY4sVyZzxSM0nIKM3Z3eBJ4pNLLRb3J3L6qVSYpp7azj6vjKwS4zJL19x7FNmG4329mrWv7xX9w55dioCpKtTOOrVOxoqwkWTG7zYXCSs99sjGcOGLXadgY47RMbJQ5dFkUJIF8umKA5t21wFeEuApDZWZ2iD/j+IH7Znb+0GK4l5S2+SoU4fCXB+nTVq1HR6uwueLxZCiFjUCG7TK0kjb7FJoMEUSi95XwbLColIenCDWro3gj0u+RpsR6txQ4P9lRwjUQVh211zhH2UGA+78HGpNn2UoOClqLsjPRLXGXpze5f3d1ctgzF2V62zx0fu2591o8cQrGVJxIZ7C0DpTRd6690zSSC/YvWcYfnWf8iVkpf2Q4t1UJZiw4IEJqahvL49W5krqzzX1Ml99l5DA7gqK/LuxvDneY8TWYPgZDGu0pioTXWA1zSTXbSNnr3IsrObqloxMkH14t6wtFrSpamOIOni1EO/wy0FKNp1UZNJ8ouvaNA/fmOBBc4f9xqhwaG7ehMp3K1CNWwA4FHJUvTADaoQaCLG/0ZMDbwTbLRhY7kPOGCEoCAeIXDnOCIO+Rmx/ZF1AIfkVJ7VqYiYWFZGktUgg/KSyApAUZoOpqTfU9zc5T5EFg5IAssp5i3hMW8iPPy6ymUFDxjfi1TpTW+v1w0v4TCAfZtK4uygAtmknKjrl7mSGnmfv7tEfid6p0vPVhAk3bEPjcXA+37I2Z1YtL+USnAlUdnuFJgxey15wO2kPQNqyTX/8Lt2m5aKHMfpTyvjwyb5/7QkNfzZogR64B24xvP7KWZu/VSXBWHSqWLu3q0XVyWccLs3CejDW+RF7k7uY9yCV2eB/DHXl0UNV2P7Z6yQpmyvGzjWAtUVnFtOc66eKYtMJhqZuzSZIY2XPzMayKs/2v7wEyGJdXJl8hSperdrVahlgVSQg8FTkB4m,iv:3xz0KJMH18eCPDCTGIUvDVXbT2mrdqKvj40XqdeWkbs=,tag:HpcpMyMYPmPmYVoD7ERH2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16jt3lh4knprgtjdkt3st2w8ntqfc2czjkz20vf3gvnlxw92sqdjs3swhhz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBReE9OUDZYZ25kc202Rkp1
            U25ONk5nR3VqV3VSOVRKQWs0VGQxYkFScTJVCkpjMmp5VFgvSTRFVllmaVZEN2w1
            WDhBRzdRVDYrWDdtd2ZEVHBDdmFLZGsKLS0tIHBERVlOT2JaWDh6dDI1M0VSM2R0
            L1I0cEUrb2paMlBTVlFtb3FYamdreXMKpyJNJXlYcOWOMfF5R/jpSstSzTWY94Ws
            lcLXK/+ST+TjShv1gmhAwOjGqCCLUP48pnEpuIA4Suem38BYJPJLNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-15T18:01:47Z"
    mac: ENC[AES256_GCM,data:J/lWOEtsLXmIX03QZqqjMy3B8E/kTe3PfWAtHYxXqzLhzfiywsgmlcDOxjfxKb4iGbBwwUkUtEFCfOEhTiLIyczito4bVeF5K6FmCf1AE/TjXXmx4R+bgk2JASuuz9/9Wv6IuBRtgfZOO7C3u09Zcidsf2f+fzST/c8CrOobd8c=,iv:ZO+7z9ukC9Zxbx3jAO47HngjVdtTbda+Sk2yVJdHBLA=,tag:kiiGovd43ZupyYtDEi/5qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
