[env]
KUBECONFIG = "{{config_root}}/kubeconfig"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
TALOSCONFIG = "{{config_root}}/talos/clusterconfig/talosconfig"

[tools]
"aqua:budimanjojo/talhelper" = "3.0.39"
"aqua:cilium/cilium-cli" = "0.18.8"
"aqua:cli/cli" = "2.83.0"
"aqua:cloudflare/cloudflared" = "2025.10.1"
"aqua:derailed/k9s" = "0.50.16"
"aqua:FiloSottile/age" = "1.2.1"
"aqua:fluxcd/flux2" = "2.7.3"
"aqua:getsops/sops" = "3.11.0"
"aqua:go-task/task" = "3.45.4"
"aqua:helm/helm" = "3.19.0"
"aqua:helmfile/helmfile" = "1.1.9"
"aqua:jqlang/jq" = "1.7.1"
"aqua:kubernetes-sigs/kustomize" = "5.6.0"
"aqua:kubernetes/kubectl" = "1.33.1"
"aqua:mikefarah/yq" = "4.48.1"
"aqua:mitsuhiko/minijinja" = "2.12.0"
"aqua:siderolabs/talos" = "1.11.5"
"aqua:stern/stern" = "1.33.1"
