[env]
KUBECONFIG = "{{config_root}}/kubeconfig"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
TALOSCONFIG = "{{config_root}}/talos/clusterconfig/talosconfig"

[tools]
"aqua:budimanjojo/talhelper" = "3.1.0"
"aqua:cilium/cilium-cli" = "0.18.9"
"aqua:cli/cli" = "2.83.2"
"aqua:cloudflare/cloudflared" = "2025.11.1"
"aqua:derailed/k9s" = "0.50.18"
"aqua:FiloSottile/age" = "1.3.1"
"aqua:fluxcd/flux2" = "2.7.5"
"aqua:getsops/sops" = "3.11.0"
"aqua:go-task/task" = "3.46.4"
"aqua:helm/helm" = "3.19.4"
"aqua:helmfile/helmfile" = "1.2.3"
"aqua:jqlang/jq" = "1.7.1"
"aqua:kubernetes-sigs/kustomize" = "5.6.0"
"aqua:kubernetes/kubectl" = "1.33.1"
"aqua:mikefarah/yq" = "4.50.1"
"aqua:mitsuhiko/minijinja" = "2.13.0"
"aqua:siderolabs/talos" = "1.12.1"
"aqua:stern/stern" = "1.33.1"
