---
# yaml-language-server: $schema=https://kubernetes-schemas.perry.cafe/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: minecraft
  values:
    deploymentAnnotations:
      secret.reloader.stakater.com/reload: &secret minecraft
    image:
      repository: ghcr.io/itzg/minecraft-server
      tag: 2025.12.0-java21
    resources:
      limits:
        memory: 8Gi
      requests:
        cpu: 100m
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    livenessProbe:
      initialDelaySeconds: 0
    readinessProbe:
      initialDelaySeconds: 0
    startupProbe:
      enabled: true
    extraEnv:
      TZ: "America/Los_Angeles"
      ENABLE_ROLLING_LOGS: true
      UID: 1000
      GID: 1000
      MEMORY: ""
    persistence:
      dataDir:
        enabled: true
        existingClaim: "${APP}"
    serviceAnnotations:
      lbipam.cilium.io/ips: "192.168.1.205"
    minecraftServer:
      eula: true
      # renovate: datasource=custom.minecraft-release
      version: 1.21.8
      type: FABRIC
      difficulty: normal
      pvp: false
      motd: Hello
      worldSaveName: "Perry's Cafe"
      viewDistance: 26
      forceReDownload: true
      memory: ""
      jvmXXOpts: "-XX:MaxRAMPercentage=70"
      rcon:
        enabled: true
        serviceType: ClusterIP
      serviceType: LoadBalancer
      extraPorts:
        - name: map
          containerPort: 8100
          protocol: TCP
          service:
            enabled: true
            embedded: false
            type: ClusterIP
            port: 8100
        - name: metrics
          containerPort: 25585
          protocol: TCP
          service:
            enabled: true
            embedded: false
            type: ClusterIP
            port: 25585
      modrinth:
        projects:
          - distanthorizons:beta
          - essential-commands
          - fabricexporter
          - ferrite-core
          - lithium
        downloadDependencies: required
  valuesFrom:
    - kind: Secret
      name: *secret
      valuesKey: RCON_PASSWORD
      targetPath: minecraftServer.rcon.password
