---
# yaml-language-server: $schema=https://kubernetes-schemas.perry.cafe/k8s.cni.cncf.io/networkattachmentdefinition_v1.json
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: home
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "home",
      "plugins": [
        {
          "type": "macvlan",
          "master": "enp86s0",
          "mode": "bridge",
          "capabilities": { "ips": true, "mac": true },
          "ipam": {
            "type": "static",
            "subnet": "192.168.1.0/24",
            "gateway": "192.168.1.1"
          }
        },
        {
          "type": "sbr"
        }
      ]
    }
