---
# yaml-language-server: $schema=https://kubernetes-schemas.perry.cafe/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plugin-barman-cloud
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: plugin-barman-cloud
  values:
    namespaceOverride: database
    image:
      registry: ghcr.io
      repository: cloudnative-pg/plugin-barman-cloud
      tag: v0.8.0@sha256:c3e423094c70c333a41a38dd781f0d9a9e539a2b9a2e4fe9e49224f65b4c84d6
    sidecarImage:
      registry: ghcr.io
      repository: cloudnative-pg/plugin-barman-cloud-sidecar
      tag: v0.8.0@sha256:9fd962189068dc3351edf8bce95949987300eac99acf843c8fcc1f0af25f8960
