---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./atuin/ks.yaml
  - ./cyberchef/ks.yaml
  - ./maddy/ks.yaml
  - ./miniflux/ks.yaml
  - ./opnsense/ks.yaml
  - ./pikvm/ks.yaml
  - ./paperless/ks.yaml
  - ./thelounge/ks.yaml
