---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app opnsense-exporter
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: opnsense-exporter
  values:
    controllers:
      opnsense-exporter:
        containers:
          app:
            image:
              repository: ghcr.io/athennamind/opnsense-exporter
              tag: 0.0.11@sha256:7c5977edd1304af762bb3908dbe0cab259ccd7cb73f1fc98a43a28185d7efea3
            args:
              # - --log.level=debug
              # - --log.format=json
              - --web.listen-address=:8080
            env:
              OPNSENSE_EXPORTER_INSTANCE_LABEL: "gw"
              OPNSENSE_EXPORTER_DISABLE_OPENVPN: "true"
              OPNSENSE_EXPORTER_OPS_API: "192.168.1.1"
              OPNSENSE_EXPORTER_OPS_INSECURE: true
              OPNSENSE_EXPORTER_OPS_PROTOCOL: https
            envFrom: &envFrom
              - secretRef:
                  name: opnsense-exporter-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources: &resources
              limits:
                memory: 128Mi
              requests:
                cpu: 10m
            securityContext: &securityContext
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
      check-firmware-update:
        type: cronjob
        cronjob:
          schedule: "@daily"
          failedJobsHistory: 1
          successfulJobsHistory: 0
          timeZone: "America/Los_Angeles"
        containers:
          app:
            image:
              repository: docker.io/alpine/curl
              tag: 8.14.1@sha256:933740ea568f85d2d9ceb4006c68df9af245d777eceff0e09af71c3c295665a5
            args:
              - "--fail"
              - "--silent"
              - "--show-error"
              - "--location"
              - "--insecure"
              - "--request"
              - POST
              - "--user"
              - >-
                $(OPNSENSE_EXPORTER_OPS_API_KEY):$(OPNSENSE_EXPORTER_OPS_API_SECRET)
              - "--data"
              - "{}"
              - https://opnsense.home.arpa/api/core/firmware/status
            envFrom: *envFrom
            resources: *resources
            securityContext: *securityContext
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8080
    serviceMonitor:
      app:
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
