---
# yaml-language-server: $schema=https://kubernetes-schemas.perry.cafe/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "perryhuynh-com-production"
spec:
  dnsNames:
    - perryhuynh.com
    - "*.perryhuynh.com"
  duration: 160h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 384
    rotationPolicy: Always
  secretName: "perryhuynh-com-production-tls"
  usages:
      - digital signature
---
# yaml-language-server: $schema=https://kubernetes-schemas.perry.cafe/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: perry-cafe-production
spec:
  dnsNames:
    - perry.cafe
    - "*.perry.cafe"
  duration: 160h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 384
    rotationPolicy: Always
  secretName: perry-cafe-production-tls