---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./configmap.yaml
  - ./helmrelease.yaml
  - ./prometheusrule.yaml
configMapGenerator:
  - name: rfc1628-ups-dashboard
    files:
      - ups-dashboard.json=./resources/dashboard.json
    options:
      labels:
        grafana_dashboard: "true"
  - name: rfc1628-ups-configmap
    files:
      - snmp.yaml=./resources/snmp.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
